import { useEffect, useRef, useState } from 'react'
import { get, patch, post } from '../api/client'
import { Badge, Empty, Modal } from '../components/UI'
import { clp, date, urgency } from '../utils'

export default function CuentasPorCobrar() {
 const [docs,setDocs]=useState([]),[state,setState]=useState(''),[filter,setFilter]=useState(''),[term,setTerm]=useState(''),[message,setMessage]=useState(''),[result,setResult]=useState(null),[importing,setImporting]=useState(false); const file=useRef()
 const load=()=>get('/documentos', {params:state?{estado:state}:{}}).then(setDocs).catch(()=>setMessage('No se pudieron cargar los documentos.'))
 useEffect(() => { void load() },[state]); const visible=docs.filter(d=>(!filter||urgency(d.fecha_vencimiento)[0]===filter)&&`${d.clientes?.nombre||''} ${d.numero_documento}`.toLowerCase().includes(term.toLowerCase()))
 async function paid(id){ await patch(`/documentos/${id}`,{estado:'pagado'}); setMessage('Documento marcado como pagado.'); load() }
 async function upload(e){const selected=e.target.files?.[0];if(!selected)return; const form=new FormData();form.append('archivo',selected);setImporting(true);setMessage('');try{const summary=await post('/documentos/importar-excel',form);setResult(summary);await load()}catch(err){const detail=err.response?.data?.detail;const status=err.response?.status;setMessage(status===401?'No autorizado: revisa la API key.':detail||'No fue posible importar el archivo. Revisa tu conexión e inténtalo nuevamente.')}finally{setImporting(false);e.target.value=''}}
 return <><header><p className="eyebrow">COBRANZA</p><h1>Cuentas por cobrar</h1></header><div className="toolbar"><input placeholder="Buscar cliente o documento…" value={term} onChange={e=>setTerm(e.target.value)}/><select value={state} onChange={e=>setState(e.target.value)}><option value="">Todos los estados</option><option value="pendiente">Pendientes</option><option value="pagado">Pagados</option><option value="anulado">Anulados</option></select><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Toda urgencia</option><option value="vencida">Vencidos</option><option value="proxima">Próximos (5d)</option><option value="vigente">Vigentes</option></select><button className="primary" disabled={importing} onClick={()=>file.current.click()}>{importing?'Importando…':'↑ Subir Excel semanal'}</button><input ref={file} type="file" accept=".xlsx" hidden onChange={upload}/></div>{importing&&<p className="notice">Importando… esto puede tardar unos segundos.</p>}{message&&<p className="notice error">{message}</p>}<section className="table panel"><div className="thead"><span>Cliente / documento</span><span>Vencimiento</span><span>Saldo</span><span>Estado</span><span/></div>{visible.length?visible.map(d=>{const [v,l]=urgency(d.fecha_vencimiento);return <div className="trow" key={d.id}><div><b>{d.clientes?.nombre||'Sin cliente'}</b><small>{d.tipo} N°{d.numero_documento}</small></div><span>{date(d.fecha_vencimiento)}</span><b>{clp(d.saldo_pendiente)}</b><Badge variant={d.estado==='pendiente'?v:''}>{d.estado==='pendiente'?l:d.estado}</Badge>{d.estado==='pendiente'?<button onClick={()=>paid(d.id)}>Marcar pagado</button>:<span/>}</div>}):<Empty/>}</section>{result&&<Modal title="Importación completada" onClose={()=>setResult(null)}><div className="import-result"><p><b>{result.filas_totales}</b> filas totales · <b>{result.filas_jefferson}</b> filas de Jefferson</p><p><b>{result.documentos_creados}</b> documentos creados · <b>{result.documentos_actualizados}</b> actualizados</p><p><b>{result.clientes_nuevos}</b> clientes nuevos</p>{result.errores?.length>0&&<><h3>Filas con errores ({result.errores.length})</h3>{result.errores.map(x=><p key={x.fila}>Fila {x.fila}: {x.error}</p>)}</>}{!result.errores?.length&&<p>Importación realizada sin errores.</p>}</div></Modal>}</>
}
